[tox]
envlist=
  py3.8-3.2
  py3.8-4.{0,1.2}
  py3.9-3.2
  py3.9-4.{0,1,2}
  py3.10-3.2
  py3.10-4.{0,1,2}
  py3.10-5.{0,1}
  py3.10-djdev
  py3.11-4.{1,2}
  py3.11-5.{0,1}
  py3.11-djdev
  py3.12-4.2
  py3.12-5.{0,1}
  py3.12-djdev
  py3.13-5.1
  py3.13-djdev

[testenv]
basepython =
  py3.9: python3.9
  py3.10: python3.10
  py3.11: python3.11
  py3.12: python3.12
  py3.13: python3.13
commands=python setup.py test
deps =
  3.2: Django~=3.2.0
  4.0: Django~=4.0.0
  4.1: Django~=4.1.0
  4.2: Django~=4.2.0
  5.0: Django~=5.0.0
  5.1: Django~=5.1.0
  djdev: https://github.com/django/django/archive/main.tar.gz
